spring:
  application:
    name: finance-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finance?allowMultiQueries=true&useUnicode=true&useSSL=false
    username: root
    password: root
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mail:
    host: smtp.163.com
    username: befairytale@163.com
    password: syb792521
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: utf-8
#  redis:
#    host: localhost
#    port: 6379
#    password:
server:
  port: 1099

#mybatis
mybatis-plus:
  # config-location:
  # classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mapper/finance/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.blackey.finance.*.domain
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
  global-config:
    # 刷新mapper 调试神器
    refresh: true
    banner: false
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    # 数据库相关配置
    db-config:
      db-type: mysql
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
      # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0

redis:
  serializer:
    name: kryo
management:
  security:
    enabled: false

application:
  captcha:
    enabled: false
logging:
  level:
    com.blackey.artisan.component.mapper: debug
file:
  upload:
    path: /opt/application/finance/
http:
  domain:
   base: http://127.0.0.1:1099
   access:
    path: http://127.0.0.1:1099/opt/application/finance/
wx:
  miniapp:
    configs:
      - appid: wx30a31ffd0cc7494f
        secret: 8ae975c75c3f18f0a94cbbd5764544e5
        token:
        aesKey:
        msgDataFormat: JSON

blackey:
  swagger2:
    basePackage: com.blackey.finance.rest
  file:
    upload:
      serverName: artisan
      remoteAddress: /opt/
      serverDomain: http://localhost/