spring:
  application:
    name: flowers-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:8889/flowers?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
#  redis:
#    host: localhost
#    port: 6379
#    password:
server:
  port: 1099

#mybatis
mybatis-plus:
  # config-location:
  # classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mapper/flowers/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.blackey.flowers.*.domain
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
  global-config:
    # 刷新mapper 调试神器
    refresh: true
    banner: false
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    # 数据库相关配置
    db-config:
      db-type: mysql
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
      # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0

redis:
  serializer:
    name: kryo

application:
  captcha:
    enabled: false

logging:
  level:
    org.springframework.web: INFO
    com.blackey.flowers.component.mapper: debug
    me.chanjar.weixin: DEBUG

file:
  upload:
    path: /opt/application/flowers/
http:
  domain: http://portal.chihei/opt/application/artisan/
wx:
  miniapp:
    configs:
      - appid: wxa8fd746b43616ab5
        secret: b21e12ec6a15eb52c8ce1a7ceb63014f
        token:
        aesKey:
        msgDataFormat: JSON
  pay:
    appId: wxa8fd746b43616ab5
    mchId: 1501919461
    mchKey: A1B2A1B2A1B2A1B2A1B2A1B2A1B2A1B2
    keyPath: # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
blackey:
  swagger2:
    basePackage: com.blackey.flowers.rest